### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thgh** [StadGent/laravel_site_opening-hours#1]
- [x] API > Users > create: Should return the user object after creation
- [x] API > Channel > create: Should return 422 if label is empty
- [x] API > Channel > create: Should add myself as owner by default
- [x] API > Services: service.users should return the role of each user in that service
